### ISSUE TITLE
Rx Extension flowable doOnTerminate never called after Disposable dispose

### ISSUE THREAD

**Issue by danielceinos** [minikorp/mini#7]
Disposing the `Disposable` after call `Store<S>.flowable` doesnt exec `doOnTerminate` so the store's listener is never removed

**Comment by pabloogc** [comment]
Writing fix and test for it

**Comment by pabloogc** [comment]
For some reason flowable does not have a `doOnDispose` method, so no way to control that case. I  removed flowable implementation (you can still call `toFlowable` on the observable from rx) and fixed the observable bug

**Comment by pabloogc** [comment]
Fixed in 5.0.1

**Comment by danielceinos** [comment]
I saw that `Flowable` has the `doFinally` operator, could it be used safely for cancel the store subscription?

**Comment by pabloogc** [comment]
Yeah, found that after a while, no clue why they named them same way, but after reading a bit I prefer to keep only the observable method so if you need backpressure you set the strategy specifically (should never be needed for UI, so it was just overhead before)
